# Generated by Django 5.2.9 on 2026-03-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_loss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='picture',
        ),
        migrations.CreateModel(
            name='WeightRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weight_pics/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weight_loss.weightrecord')),
            ],
        ),
    ]
